#!/usr/bin/env python3
"""Genera original/curso-v2-semanas-1-2.html: los días 1-14 del curso v2 (muestra).

El contenido sigue curso-v2/especificacion-v2.md (día tipo de 7 bloques, criterios
escalonados, cero referencias vagas). Los diagramas de acordes se copian del
original congelado para mantener la misma fuente visual.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
ORIGINAL = ROOT / "original" / "curso_guitarra_6_meses_182_dias.html"
OUT = ROOT / "original" / "curso-v2-semanas-1-2.html"

_svg_cache = {}


def chord_svgs(names):
    if not names:
        return ""
    html = ORIGINAL.read_text(encoding="utf-8")
    out = []
    for n in names:
        if n not in _svg_cache:
            m = re.search(
                rf'<div class="chord"><b>{re.escape(n)}</b><svg.*?</svg></div>', html, re.S
            )
            if not m:
                raise SystemExit(f"acorde sin diagrama en el original: {n}")
            _svg_cache[n] = m.group(0)
        out.append(_svg_cache[n])
    return '<div class="chords">' + "".join(out) + "</div>"


def ex(title, mins, brief, steps, watch, crit, chords=()):
    return {
        "t": title, "min": mins, "brief": brief, "steps": steps,
        "watch": watch, "crit": crit, "chords": chords,
    }


ACT = ex(
    "Activación",
    2,
    "Ritual de entrada: postura y péndulo. Igual todos los días.",
    [
        "Silla estable, mástil algo elevado, pulgar izquierdo detrás del mástil, hombros sueltos.",
        "Metrónomo a 60 BPM: mano derecha como péndulo al aire (abajo en el clic, arriba entre clics), 8 compases sin tocar cuerdas.",
        "Suelta hombros y brazos 2 segundos y retoma; termina con 4 compases de péndulo sobre cuerdas apagadas.",
    ],
    "El péndulo no se detiene nunca; la tensión se va en cada aflojada.",
    "8 compases de péndulo parejo sin tensión.",
)


def cierre(prog, extra=""):
    return ex(
        "Cierre · registro",
        1,
        "Una vuelta perfecta y anotar los récords del día.",
        [
            f"Una vuelta lenta e impecable de {prog} (elige tú el BPM: el que garantice cero errores)." ,
            "Anota en las notas de la app los récords del día: BPM máximos y cambios por minuto." + (" " + extra if extra else ""),
        ],
        "Terminar limpio fija lo practicado; terminar corriendo fija errores.",
        "La vuelta sale limpia y los récords quedan anotados.",
    )


DAYS = []

# ───────────────────────── SEMANA 1 · Línea base acelerada ─────────────────────────
W1 = "Línea base acelerada"

DAYS.append({  # Día 1
    "tema": W1, "modo": "Aprender", "foco": "Arranque de todos los hilos",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-i-m-a", 5,
           "Arranca el hilo nuevo: arpegio con dedos asignados, en Am.",
           ["Asignación fija: p=5ª cuerda, i=3ª, m=2ª, a=1ª. La mano no salta: cada dedo tiene su cuerda.",
            "Con Am pisado, toca p-i-m-a ascendente, una nota por clic. Metrónomo a 50 BPM.",
            "Cada 2 compases limpios sube 5 BPM; 2 fallos seguidos, baja 5.",
            "Últimos 60 segundos: p-i-m-a con los ojos en la mano derecha, cuidando que cada dedo toque solo su cuerda."],
           "Las cuatro notas suenan con volumen parejo (la de a suele salir débil).",
           "8 compases limpios a 55 BPM o más; anota tu BPM máximo."),
        ex("Cejilla · traste 7, cuerdas 1-3", 4,
           "Primera micro-dosis: la cejilla parte donde es fácil (trastes altos).",
           ["Dedo 1 recto y algo de canto (lado del hueso, no la yema plana) cruzando cuerdas 1, 2 y 3 en el traste 7.",
            "Pulgar detrás del mástil, a la altura del dedo 2, empujando suave: la fuerza es pinza pulgar-índice, no apretón de muñeca.",
            "Presiona 5 segundos y toca las 3 cuerdas una a una; suelta 5 segundos. Repite 8 veces.",
            "Busca la presión MÍNIMA que hace sonar las 3: menos fuerza de la que crees."],
           "Que no duela la muñeca; si duele, el pulgar está mal puesto o estás apretando de más.",
           "En 3 de los 8 intentos suenan las 3 cuerdas limpias."),
        ex("Ritmo · línea base de péndulo", 6,
           "Verifica en 1 minuto lo que ya tienes y empieza donde te corresponde.",
           ["Metrónomo a 60 BPM. Test de 1 minuto: C-G-Am-Em, un rasgueo ↓ por pulso, un compás por acorde.",
            "Si los 8 compases salieron limpios a la primera: pasa a corcheas ↓↑ (abajo en el número, arriba en el 'y') sobre cuerdas apagadas, 4 compases, y luego con los acordes.",
            "Si no: quédate en negras y sube 5 BPM cada 4 compases limpios.",
            "Los últimos 2 minutos: la variante más difícil que te haya salido, 8 compases seguidos."],
           "La derecha nunca se detiene cuando la izquierda cambia de acorde.",
           "16 compases estables; anota si quedaste en negras o corcheas y a qué BPM.",
           chords=("C", "G", "Am", "Em")),
        ex("Cambios · C↔G y C↔Am", 4,
           "Récords de cambios con el contador por micrófono.",
           ["Abre el contador por micrófono de la app.",
            "60 segundos: alterna C↔G rasgueando un ↓ por acorde, tan rápido como salga LIMPIO. El contador cuenta tus golpes: tu récord es esa cifra.",
            "Descansa 30 segundos sacudiendo la mano.",
            "60 segundos: lo mismo con C↔Am. Anota ambos récords: son tu línea base de la semana."],
           "Los dedos que se repiten entre acordes (guía) no deben despegarse del diapasón.",
           "Dos récords anotados; hoy no hay mínimo: es tu punto de partida."),
        ex("Voz + guitarra · contar y nombrar", 8,
           "El hilo más importante para ti: la voz se monta sobre la mano ya automática.",
           ["Nivel 1 (2 min): rasguea C en negras a 60 BPM contando '1-2-3-4' EN VOZ ALTA, fuerte y parejo.",
            "Nivel 2 (2 min): C-G-Am-Em, un compás cada uno, contando en voz alta sin frenar la derecha.",
            "Nivel 3 (4 min): la misma vuelta, pero en el pulso 1 de cada compás di el NOMBRE del acorde ('do... sol... la menor... mi menor') y sigue contando mentalmente.",
            "Si la derecha se traba al hablar, baja a 55 BPM antes que dejar de hablar."],
           "La voz no puede callarse para que la mano acierte: esa es exactamente la coordinación que entrenas.",
           "8 compases seguidos nombrando acordes sin que el rasgueo se detenga."),
        cierre("C-G-Am-Em", "Anota también tu resultado del test de ritmo (negras o corcheas)."),
    ],
})

DAYS.append({  # Día 2
    "tema": W1, "modo": "Repetir y subir", "foco": "Mismos hilos, parámetros nuevos",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-i-m-a en Am→C", 5,
           "El patrón de ayer, ahora cambiando de acorde sin frenar.",
           ["Asignación de ayer: p=5ª, i=3ª, m=2ª, a=1ª.",
            "Un compás de p-i-m-a en Am, un compás en C, alternando. Metrónomo a 55 BPM.",
            "El cambio de acorde ocurre MIENTRAS p toca la 5ª: los otros dedos llegan durante esa nota.",
            "Cada 2 compases limpios sube 5 BPM; 2 fallos, baja 5."],
           "El arpegio no se corta en el cambio: si se corta, el cambio empezó tarde.",
           "8 compases alternando Am→C limpios; anota el BPM máximo."),
        ex("Cejilla · traste 7, cuerdas 1-4", 4,
           "Misma pinza de ayer, una cuerda más.",
           ["Dedo 1 cruzando cuerdas 1 a 4 en el traste 7, con algo de canto.",
            "Presiona 5 segundos, toca las 4 cuerdas una a una, suelta 5 segundos. 8 repeticiones.",
            "En cada intento afloja hasta encontrar la presión mínima que suena.",
            "Último intento: presiona y rasguea las 4 cuerdas juntas 2 veces."],
           "El codo izquierdo cae relajado hacia el cuerpo: ayuda a la cejilla más que la fuerza del dedo.",
           "En 3 de 8 intentos suenan las 4 cuerdas."),
        ex("Ritmo · corcheas con acordes", 6,
           "Del péndulo apagado a las corcheas sonando.",
           ["Metrónomo a 56 BPM: corcheas ↓↑ sobre cuerdas apagadas, 4 compases (abajo en el número, arriba en el 'y').",
            "Ahora con acordes: C-G-Am-Em, un compás cada uno, corcheas ↓↑ continuas.",
            "Cada 4 compases limpios sube 4 BPM; si un cambio detiene la derecha, vuelve a apagadas 2 compases y reintenta.",
            "Cierra con 8 compases seguidos al mejor BPM del bloque."],
           "El ↑ es más suave que el ↓ (toca menos cuerdas): así suena a música y no a metrónomo.",
           "16 compases de corcheas estables; anota el BPM."),
        ex("Cambios · G↔Am y C↔D", 4,
           "Dos pares nuevos, mismo formato de récord.",
           ["Contador por micrófono: 60 segundos G↔Am, un ↓ por acorde, rápido pero limpio.",
            "30 segundos de descanso.",
            "60 segundos C↔D. En C→D los dedos se reordenan enteros: mueve el bloque completo, no dedo por dedo.",
            "Anota ambos récords."],
           "Mira la mano izquierda SOLO en el aterrizaje del acorde nuevo, no durante el viaje.",
           "Dos récords anotados.",
           chords=("D",)),
        ex("Voz + guitarra · tararear la tónica", 8,
           "De hablar a sostener una nota afinada mientras tocas.",
           ["Nivel 1 (2 min): rasguea C en negras a 58 BPM y tararea ('mmm') la nota DO sostenida. Sácala del propio acorde: toca la 2ª cuerda traste 1 antes de empezar.",
            "Nivel 2 (2 min): lo mismo en G tarareando SOL (3ª cuerda al aire).",
            "Nivel 3 (4 min): C-G alternando por compás, moviendo el tarareo do→sol en cada cambio, sin cortar el rasgueo.",
            "Si te desafinas, para el rasgueo, vuelve a pescar la nota de la cuerda y retoma."],
           "El tarareo debe sostenerse DURANTE el cambio de acorde: ahí es donde se corta siempre.",
           "8 compases de C-G con el tarareo afinado y continuo."),
        cierre("C-G-Am-Em"),
    ],
})

DAYS.append({  # Día 3
    "tema": W1, "modo": "Repetir y subir", "foco": "Patrón inverso y grados cantados",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-a-m-i", 5,
           "El arpegio al revés: baja en vez de subir.",
           ["Misma asignación: p=5ª, a=1ª, m=2ª, i=3ª. Ahora el orden es p-a-m-i (grave, agudo y de vuelta).",
            "Un compás en Am, un compás en C, a 55 BPM.",
            "Cada 2 compases limpios sube 5 BPM; 2 fallos, baja 5.",
            "Último minuto: alterna un compás p-i-m-a y un compás p-a-m-i sin parar (la mezcla es el ejercicio)."],
           "En p-a-m-i el dedo a manda: si a suena débil, todo el patrón se cae.",
           "8 compases de p-a-m-i limpios; anota el BPM máximo."),
        ex("Cejilla · traste 5, cuerdas 1-4", 4,
           "Un paso hacia la cejuela: más tensión de cuerda, misma técnica.",
           ["Dedo 1 en cuerdas 1-4, traste 5. Pinza pulgar-índice, codo caído.",
            "5 segundos presionando y tocando cuerda a cuerda, 5 de descanso, 8 repeticiones.",
            "Si una cuerda no suena, no aprietes más: rueda el dedo un milímetro hacia el canto y reintenta."],
           "Las falanges no se doblan hacia atrás: el dedo es una barra recta.",
           "En 3 de 8 intentos suenan las 4 cuerdas."),
        ex("Ritmo · patrón ↓ ↓↑ ↓ ↓↑", 6,
           "Primer patrón real: mezcla negras y corcheas.",
           ["El patrón por compás es: ↓ (pulso 1), ↓↑ (pulso 2), ↓ (3), ↓↑ (4). El péndulo sigue moviéndose siempre; en los pulsos 1 y 3 el ↑ pasa sin tocar.",
            "Metrónomo a 58 BPM: 4 compases sobre cuerdas apagadas.",
            "Con acordes: C-G-Am-Em, un compás cada uno.",
            "Cada 4 compases limpios sube 4 BPM; cierra con 8 compases seguidos al mejor BPM."],
           "El brazo no cambia de velocidad: el patrón nace de tocar o no tocar, no de acelerar la mano.",
           "16 compases del patrón estables; anota el BPM."),
        ex("Cambios · D↔Em y Am↔Em", 4,
           "Récords con el contador por micrófono.",
           ["60 segundos D↔Em: fíjate qué dedo puede viajar menos y úsalo de guía.",
            "30 segundos de descanso.",
            "60 segundos Am↔Em: casi todos los dedos se reutilizan; el cambio debería ser el más rápido que tengas.",
            "Anota ambos récords."],
           "Manos cerca del diapasón: los dedos que vuelan alto llegan tarde.",
           "Dos récords anotados; Am↔Em debería superar los récords de ayer."),
        ex("Voz + guitarra · cantar grados 1-2-3-2-1", 8,
           "De la nota sostenida a una mini-melodía cantada.",
           ["Nivel 1 (3 min): rasgueando C en negras a 58 BPM, canta 'do-re-mi-re-do' (un grado por pulso, el 5º pulso cae en el compás siguiente). Referencia: do=2ª cuerda traste 1, re=1ª al aire... tócalas antes si lo necesitas.",
            "Nivel 2 (3 min): lo mismo en G cantando 'sol-la-si-la-sol'.",
            "Nivel 3 (2 min): alterna un compás C (do-re-mi-re-do) y un compás G (sol-la-si-la-sol) sin frenar la derecha.",
            "Desafinarse está permitido; callarse no."],
           "La voz sube y baja mientras la mano repite lo mismo: son carriles separados.",
           "4 compases afinados sobre C y 4 sobre G."),
        cierre("C-G-Am-Em"),
    ],
})

DAYS.append({  # Día 4
    "tema": W1, "modo": "Repetir y subir", "foco": "El gap: arpegio sin pulgar (m-a)",
    "ex": [
        ACT,
        ex("Arpegio digitado · sin pulgar (i-m, m-a, a-m)", 5,
           "Directo a tu punto débil: pares de dedos sin el ancla del pulgar.",
           ["Con Am pisado, i=3ª cuerda, m=2ª, a=1ª. Metrónomo a 50 BPM, una nota por clic.",
            "1 minuto i-m alternando (3ª-2ª-3ª-2ª...).",
            "2 minutos m-a (2ª-1ª-2ª-1ª...): TU ejercicio. Volumen parejo entre medio y anular; el anular tiende a sonar la mitad.",
            "1 minuto a-m (empieza el débil).",
            "1 minuto m-a de nuevo, subiendo 5 BPM si va limpio."],
           "El dedo que no toca se queda cerca de su cuerda, no se esconde en la palma.",
           "4 compases de m-a parejos a 55 BPM; anota el BPM."),
        ex("Cejilla · traste 5, las 6 cuerdas", 4,
           "Primera cejilla completa (donde es amable).",
           ["Dedo 1 cruzando las 6 cuerdas en el traste 5, con canto, pulgar detrás a la altura del dedo 2.",
            "5 segundos presionando y tocando cuerda a cuerda de 6ª a 1ª, 5 de descanso, 8 repeticiones.",
            "Las que no suenen, identifícalas: casi siempre 3ª y 4ª (van en las articulaciones del dedo); rueda el dedo hasta pillarlas."],
           "El hombro izquierdo no se levanta: la fuerza es de pinza, no de brazo.",
           "En 3 de 8 intentos suenan 4 o más cuerdas."),
        ex("Ritmo · D-DU-UD-U", 6,
           "El patrón universal del acompañamiento.",
           ["Por compás: ↓ (1), ↓↑ (2), ↑ (del 3, sin el ↓) y ↓↑ (4). Dicho como se siente: DOWN, DOWN-UP, UP-DOWN-UP.",
            "Metrónomo a 56 BPM: 4 compases apagados, contando '1, 2 y, y 3 y 4 y' si ayuda.",
            "Con acordes: C-G-Am-Em, un compás cada uno.",
            "Cada 4 compases limpios sube 4 BPM."],
           "El truco está en el pulso 3: el péndulo baja igual pero SIN tocar; si tocas el 3, el patrón se cuadra y pierde el groove.",
           "16 compases del patrón; anota el BPM."),
        ex("Cambios · C↔Em y G↔D", 4,
           "Dos pares nuevos a récord.",
           ["60 segundos C↔Em con el contador por micrófono.",
            "30 segundos de descanso.",
            "60 segundos G↔D: el dedo 3 puede quedarse en la 2ª cuerda traste 3 como pivote... compruébalo.",
            "Anota ambos récords."],
           "Cada acorde debe SONAR entero antes de abandonarlo: cambios que no suenan no cuentan.",
           "Dos récords anotados."),
        ex("Voz + guitarra · anticipar el acorde", 8,
           "Hablar del futuro mientras tocas el presente.",
           ["C-G-Am-Em en corcheas ↓↑ a 56 BPM.",
            "Nivel 1 (3 min): di el nombre del acorde en el pulso 1 de SU compás (como el día 1, pero en corcheas).",
            "Nivel 2 (5 min): di el nombre del acorde SIGUIENTE en el pulso 4 del compás anterior ('...sol' mientras aún tocas C). Esto es leer adelantado: la base de cantar tocando.",
            "Si la derecha se traba, baja a negras, no te calles."],
           "La boca va un compás adelante y la mano no se entera: si la mano duda, el nivel 2 aún no está.",
           "8 compases anticipando sin frenar el rasgueo."),
        cierre("C-G-Am-Em"),
    ],
})

DAYS.append({  # Día 5
    "tema": W1, "modo": "Repetir y subir", "foco": "m-a a fondo y acentos",
    "ex": [
        ACT,
        ex("Arpegio digitado · m-a a fondo", 5,
           "El par débil recibe el bloque completo.",
           ["Con Am: 90 segundos de m-a (2ª-1ª) a 50 BPM, buscando volumen idéntico entre ambos dedos.",
            "30 segundos i-m y 30 segundos a-m (contraste).",
            "Con C: 90 segundos m-a de nuevo. Cambia el acorde, el patrón es el mismo.",
            "Escalera: 2 compases limpios → +5 BPM; 2 fallos → −5.",
            "Cierra con 30 segundos al BPM máximo logrado."],
           "El anular no puede 'ayudarse' del meñique: si el meñique se mueve en espejo, va tenso.",
           "8 compases de m-a parejos; anota el BPM máximo (tu métrica de la semana)."),
        ex("Cejilla · traste 3, cuerdas 1-4", 4,
           "Cada día un traste más cerca del 1.",
           ["Dedo 1 en cuerdas 1-4, traste 3. Misma rutina: 5 segundos presionando y sonando cuerda a cuerda, 5 de descanso, 8 veces.",
            "Aquí la tensión de cuerda ya se siente: compensa con el codo caído y el pulgar bien bajo, no con apretón.",
            "Última repetición: rasguea las 4 cuerdas juntas 2 veces."],
           "Si la muñeca se dobla en L, el pulgar está muy alto.",
           "En 3 de 8 intentos suenan las 4 cuerdas."),
        ex("Ritmo · acentos", 6,
           "Mismo péndulo, ahora con dinámica: el paso previo al groove.",
           ["Corcheas ↓↑ continuas en C-G-Am-Em a 58 BPM.",
            "2 minutos acentuando los pulsos 1 y 3 (esos ↓ más fuertes, todo lo demás suave).",
            "2 minutos acentuando 2 y 4 (el backbeat: esto es lo que hace sonar 'a canción').",
            "2 minutos alternando un compás 1-3 y un compás 2-4.",
            "Sube 4 BPM cuando el acento sea obvio para un oyente."],
           "El acento es diferencia de volumen, no de velocidad: el péndulo no se acelera.",
           "8 compases con backbeat (2 y 4) claramente audible."),
        ex("Cambios · superar récords", 4,
           "Vuelven los pares del día 1: hoy se baten.",
           ["60 segundos C↔G con el contador: el objetivo es superar tu récord del día 1.",
            "30 segundos de descanso.",
            "60 segundos Am↔Em: batir el récord del día 3.",
            "Anota los nuevos récords junto a los viejos."],
           "Récord con acordes sucios no vale: limpio primero, rápido después.",
           "Al menos uno de los dos récords superado."),
        ex("Voz + guitarra · cantar las tónicas", 8,
           "La mini-escala de cada acorde se reduce a su nota raíz: cantar el bajo.",
           ["C-G-Am-Em en negras a 58 BPM.",
            "Nivel 1 (3 min): en el pulso 1 de cada compás canta la tónica del acorde con su nombre: 'do... sol... la... mi'. Son 4 notas distintas: la melodía más simple posible.",
            "Nivel 2 (3 min): sostén cada tónica el compás entero (do-o-o-o | sol-o-o-o...).",
            "Nivel 3 (2 min): lo mismo con corcheas ↓↑ en la derecha.",
            "Referencias si te pierdes: do=2ª/1, sol=3ª/0, la=3ª/2, mi=4ª/2."],
           "Bajar de sol a la NO es bajar: la voz salta hacia arriba aunque el acorde 'baje'. Escúchalo.",
           "8 compases con las 4 tónicas afinadas y el rasgueo continuo."),
        cierre("C-G-Am-Em"),
    ],
})

DAYS.append({  # Día 6
    "tema": W1, "modo": "Repetir y subir", "foco": "Combinar patrones y frasear",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-m-a-m", 5,
           "Patrón nuevo que esconde tu par débil adentro.",
           ["p=5ª, m=2ª, a=1ª: el patrón es p-m-a-m (el m toca dos veces por vuelta).",
            "Un compás en Am, un compás en C, a 55 BPM.",
            "Fíjate: dentro de p-m-a-m vive el m-a que entrenaste ayer. Si m-a está parejo, este patrón fluye.",
            "Escalera: 2 compases limpios → +5 BPM; 2 fallos → −5."],
           "El segundo m (después de a) es el que se apura: cae exactamente en su clic.",
           "8 compases de p-m-a-m limpios; anota el BPM."),
        ex("Cejilla · traste 1, cuerdas 1-4", 4,
           "Llegaste a la zona dura: donde vive el F.",
           ["Dedo 1 en cuerdas 1-4, traste 1: máxima tensión de cuerda. Rutina de siempre: 5 segundos sonando cuerda a cuerda, 5 de descanso, 8 veces.",
            "Todo lo aprendido junto: canto del dedo, pulgar bajo, codo caído, presión mínima.",
            "Aquí 2 de 8 intentos limpios ya es progreso real: mañana se mide en frío."],
           "Dolor de yema es normal esta semana; dolor de muñeca es técnica mal hecha: revisa el pulgar.",
           "En 2 de 8 intentos suenan las 4 cuerdas."),
        ex("Ritmo · D-DU-UD-U con acentos", 6,
           "El patrón del día 4 más la dinámica del día 5.",
           ["D-DU-UD-U en C-G-Am-Em a 58 BPM, 4 compases de repaso.",
            "Ahora acentúa el primer ↓ y el ↑ del pulso 3 (el del aire): el patrón cobra rebote.",
            "Escalera: 4 compases limpios → +4 BPM.",
            "Cierra con 8 compases seguidos al máximo BPM limpio."],
           "El acento del ↑ del 3 es lo que diferencia un rasgueo vivo de uno plano.",
           "16 compases del patrón acentuado; anota el BPM (récord de la semana)."),
        ex("Cambios · D↔Am y tu par más débil", 4,
           "Un par nuevo y una revancha a elección.",
           ["60 segundos D↔Am con el contador por micrófono.",
            "30 segundos de descanso.",
            "60 segundos del par que peor récord tenga en tus notas de la semana (revísalas y dilo en voz alta antes de partir).",
            "Anota ambos resultados."],
           "En D↔Am ningún dedo sobrevive: el bloque entero viaja. Suelta todo, vuela bajo, aterriza junto.",
           "Dos récords anotados; el par débil mejora respecto a su marca."),
        ex("Voz + guitarra · la escala y una frase", 8,
           "De grados sueltos a frases: el último peldaño antes de cantar canciones.",
           ["Nivel 1 (3 min): rasgueando C en negras a 58 BPM, canta la escala completa: do-re-mi-fa-sol-fa-mi-re-do (una nota por pulso; ocupa poco más de 2 compases).",
            "Nivel 2 (3 min): C-G-Am-Em en negras; canta la escala igual, aunque los acordes cambien debajo. La voz manda, los acordes acompañan.",
            "Nivel 3 (2 min): inventa una frase corta (4-6 notas, las que quieras de la escala) y repítela idéntica en cada vuelta de la progresión.",
            "Mañana este bloque se mide en frío."],
           "Cuando el acorde cambia y tu nota 'choca' un poco, no corrijas: sostenla y escucha cómo se resuelve.",
           "La escala completa afinada sobre la progresión, sin frenar la derecha."),
        cierre("C-G-Am-Em"),
    ],
})

DAYS.append({  # Día 7 — test frío
    "tema": W1, "modo": "Test frío", "foco": "Medir la semana sin calentar",
    "ex": [
        ex("Activación mínima", 2,
           "Hoy NO se calienta lo que se mide: solo postura.",
           ["Siéntate bien, afina (pestaña Afinador) y respira.",
            "8 compases de péndulo al aire a 60 BPM. Nada más: los tests van en frío a propósito — lo que sale en frío es lo aprendido de verdad."],
           "Resiste la tentación de 'probar un poquito' antes de cada test.",
           "Listo para medir."),
        ex("TEST · arpegio m-a", 5,
           "Tu métrica principal de la semana, en frío.",
           ["Con Am, directamente: m-a a 55 BPM, 8 compases. ¿Parejo o no? Anótalo (sí/no y BPM).",
            "Luego 8 compases de p-i-m-a alternando Am→C al BPM máximo que tengas anotado.",
            "Termina con 2 minutos de práctica libre del patrón que peor haya salido."],
           "Compara contra el día 4: ¿el m-a en frío de hoy suena como el m-a caliente de ese día?",
           "Resultados anotados (m-a sí/no + BPM; p-i-m-a BPM)."),
        ex("TEST · cejilla en traste 5", 4,
           "La cejilla completa, primera medición.",
           ["En frío: dedo 1 cruzando las 6 cuerdas en traste 5. Un solo intento: toca cuerda a cuerda y cuenta cuántas suenan. Anota el número.",
            "Segundo intento igual, 30 segundos después. Anota.",
            "El resto del bloque: rutina normal de 5 segundos × repeticiones en traste 3, cuerdas 1-4."],
           "El número de hoy es tu línea base de cejilla: la semana 2 se mide contra él.",
           "Dos mediciones anotadas (n/6 cuerdas)."),
        ex("TEST · ritmo D-DU-UD-U", 6,
           "16 compases seguidos al récord de la semana.",
           ["Pon el metrónomo al BPM récord que anotaste ayer.",
            "C-G-Am-Em con D-DU-UD-U, 16 compases seguidos. Si te caes, anota en qué compás y a qué BPM sí salió completo.",
            "Luego 2 minutos libres con acentos en 2 y 4."],
           "Caerse en el compás 14 no es fracaso: es el dato exacto de dónde estás.",
           "BPM real de 16 compases seguidos, anotado."),
        ex("TEST · cambios C↔G", 4,
           "El récord de la semana, en frío.",
           ["Contador por micrófono, 60 segundos C↔G. Anota y compara con el día 1: esa diferencia es tu semana.",
            "30 segundos de descanso.",
            "60 segundos del par que elijas para cerrar la semana."],
           "El récord en frío suele ser ~10% menor que el caliente: no te asustes, es normal y es el dato honesto.",
           "Récord C↔G de la semana anotado junto al del día 1."),
        ex("TEST · voz + guitarra", 8,
           "Lo más difícil de la semana, en frío.",
           ["C-G-Am-Em en negras: 8 compases cantando las tónicas (do-sol-la-mi). ¿Salió? Anota.",
            "La escala do-re-mi-fa-sol-fa-mi-re-do sobre la progresión, 2 pasadas.",
            "El resto del bloque: práctica libre del nivel que se haya caído.",
            "Cierra cantando tu frase inventada de ayer, si la recuerdas (si no, inventa otra y anótala con letra)."],
           "Recordar la frase de ayer ES el ejercicio: recuperar de memoria fija más que repetir.",
           "Resultados anotados: tónicas (sí/no), escala (sí/no), frase recordada (sí/no)."),
        ex("Cierre · registro semanal", 1,
           "El resumen que define la semana 2.",
           ["Junta en una nota los resultados de los 5 tests de hoy.",
            "Escribe una línea: '¿qué fue lo más difícil de la semana?' — la semana 2 le dará más minutos a eso."],
           "Este registro es el contrato contigo mismo: números, no sensaciones.",
           "Registro semanal completo en las notas de la app."),
    ],
})

# ─────────────────────── SEMANA 2 · F con cejilla y primera canción ───────────────────────
W2 = "F con cejilla y primera canción"

DAYS.append({  # Día 8
    "tema": W2, "modo": "Aprender", "foco": "F parcial: la cejilla se vuelve acorde",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-i-m-a por la progresión", 5,
           "El patrón de la semana 1 recorre ahora 4 acordes.",
           ["p=5ª, i=3ª, m=2ª, a=1ª. Un compás de p-i-m-a en cada acorde de C-G-Am-Em.",
            "Metrónomo a 55 BPM (o tu máximo anotado si es mayor).",
            "En G, p toca la 6ª cuerda en vez de la 5ª: el bajo real del acorde. Es el único ajuste.",
            "Escalera: 2 vueltas limpias → +5 BPM."],
           "El bajo (p) es el que dice qué acorde suena: si p pifia la cuerda, el acorde se pierde aunque el resto esté bien.",
           "2 vueltas completas limpias; anota el BPM."),
        ex("Cejilla · F parcial", 4,
           "La cejilla de la semana 1 aterriza en su destino: el F.",
           ["F parcial: dedo 1 aplasta cuerdas 1 y 2 en el traste 1 (mini-cejilla), dedo 2 en 3ª cuerda traste 2, dedo 3 en 4ª cuerda traste 3.",
            "5 segundos presionando y sonando las 4 cuerdas una a una, 5 de descanso, 8 repeticiones.",
            "Es la misma pinza que practicaste en traste 1 el día 6, con dos dedos más arriba.",
            "Última repetición: rasguea las 4 cuerdas juntas 2 veces. Eso ya ES un F."],
           "La mini-cejilla de 2 cuerdas necesita mucho menos fuerza que la completa: no aprietes como si fueran 6.",
           "En 3 de 8 intentos suenan las 4 cuerdas del F parcial.",
           chords=("F",)),
        ex("Ritmo · negras y corcheas con F", 6,
           "La progresión reina (C-G-Am-F) entra al curso.",
           ["C-G-Am-F (F parcial), un compás cada uno, negras ↓ a 58 BPM: 8 compases.",
            "Si va limpio, corcheas ↓↑: 8 compases más.",
            "En el compás de F rasguea SOLO las cuerdas 1-4 (evita 5ª y 6ª: no están en tu F parcial).",
            "Escalera: 4 compases limpios → +4 BPM."],
           "Llegar al F sin frenar el péndulo es el ejercicio; el sonido del F mejorará solo con los días.",
           "16 compases de C-G-Am-F sin que la derecha se detenga."),
        ex("Cambios · C↔F", 4,
           "El cambio más famoso (y más odiado) de la guitarra, a récord.",
           ["Contador por micrófono: 60 segundos C↔F (parcial), un ↓ por acorde.",
            "Truco de viaje: desde C, el dedo 1 se ACUESTA desde su traste 1 (va casi al mismo lugar); los dedos 2 y 3 bajan un piso cada uno.",
            "30 segundos de descanso, y otra vez: 60 segundos a superar el primer intento.",
            "Anota ambos récords: línea base del C↔F."],
           "No busques velocidad todavía: busca que el F SUENE en cada llegada.",
           "Dos récords de C↔F anotados."),
        ex("Voz + guitarra · nombrar y tararear con F", 8,
           "Los niveles 1-2 de la semana 1, sobre la progresión nueva.",
           ["C-G-Am-F en negras a 58 BPM.",
            "Nivel 1 (3 min): di el nombre del acorde en el pulso 1 de cada compás.",
            "Nivel 2 (5 min): tararea la tónica de cada acorde sosteniéndola el compás entero: do, sol, la, FA (fa=4ª cuerda traste 3: tócala antes para pescarla).",
            "El compás de F es donde la voz se calla sola (la mano pide toda la atención): no la dejes."],
           "Tararear DURANTE el aterrizaje del F: si la voz sobrevive al F, sobrevive a cualquier cambio.",
           "8 compases tarareando tónicas sin callarse en el F."),
        cierre("C-G-Am-F"),
    ],
})

DAYS.append({  # Día 9
    "tema": W2, "modo": "Repetir y subir", "foco": "F parcial en movimiento",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-a-m-i y m-a", 5,
           "El patrón inverso recorre la progresión; el par débil, su dosis.",
           ["Un compás de p-a-m-i en cada acorde de C-G-Am-Em, a tu BPM máximo anotado.",
            "2 vueltas limpias → +5 BPM.",
            "Últimos 90 segundos: m-a solo (2ª-1ª) en Am, al BPM récord del test del día 7, buscando superarlo."],
           "En cada cambio de acorde, a vuelve a la 1ª cuerda sin mirar: confía en la asignación fija.",
           "2 vueltas de p-a-m-i limpias + BPM de m-a anotado."),
        ex("Cejilla · F parcial + cambio Am→F", 4,
           "El F deja de ser estático.",
           ["3 repeticiones de la rutina de 5 segundos con F parcial (repaso).",
            "Cambio Am→F LENTO, sin metrónomo: arma el Am, suena, viaja al F, suena. 10 viajes.",
            "Pista: del Am al F, el dedo 1 baja de su traste 1 a acostarse en el MISMO traste; 2 y 3 bajan una cuerda cada uno manteniendo forma.",
            "Últimos viajes: intenta que el viaje dure un pulso a 50 BPM."],
           "El viaje corto es todo: los dedos de Am y F están a milímetros unos de otros.",
           "10 viajes Am→F con el F sonando en 6 de ellos."),
        ex("Ritmo · D-DU-UD-U con F", 6,
           "El patrón universal sobre la progresión reina.",
           ["C-G-Am-F con D-DU-UD-U a 56 BPM (F parcial, rasgueo cuerdas 1-4 en su compás).",
            "4 compases limpios → +4 BPM.",
            "Si el compás de F rompe el patrón, practícalo aislado: 4 compases solo de F con el patrón, luego reintegra.",
            "Cierra con 8 compases seguidos al mejor BPM."],
           "El patrón NO se simplifica en el F: mejor bajar BPM que mutilar el patrón.",
           "16 compases con patrón completo incluido el F; anota el BPM."),
        ex("Cambios · Am↔F y C↔F", 4,
           "Récord nuevo y revancha.",
           ["60 segundos Am↔F con el contador (el viaje que practicaste recién, ahora a velocidad).",
            "30 segundos de descanso.",
            "60 segundos C↔F: a superar los récords de ayer.",
            "Anota ambos."],
           "Am↔F debería ser tu cambio con F más rápido: úsalo para agarrar confianza antes del C↔F.",
           "Dos récords anotados; C↔F supera al de ayer."),
        ex("Voz + guitarra · tónicas cantadas con nombre", 8,
           "De tararear a cantar con la boca abierta.",
           ["C-G-Am-F en negras a 58 BPM.",
            "Nivel 1 (3 min): canta (no tarareo: nombre y vocal abierta) la tónica en el pulso 1: 'DO... SOL... LA... FA'.",
            "Nivel 2 (3 min): sostenla el compás entero.",
            "Nivel 3 (2 min): derecha en corcheas ↓↑, tónicas sostenidas encima.",
            "Referencias: do=2ª/1, sol=3ª/0, la=3ª/2, fa=4ª/3."],
           "Cantar abierto desafina más que tararear: es el siguiente nivel real, no un capricho.",
           "8 compases con las 4 tónicas cantadas y afinadas."),
        cierre("C-G-Am-F"),
    ],
})

DAYS.append({  # Día 10
    "tema": W2, "modo": "Aprender", "foco": "F completo",
    "ex": [
        ACT,
        ex("Arpegio digitado · m-a a récord", 5,
           "Bloque de especialización en tu par débil.",
           ["90 segundos m-a en Am a tu BPM récord: 2 compases limpios → +5 BPM.",
            "90 segundos m-a en C (mismo patrón, otra postura de izquierda).",
            "60 segundos a-m (el espejo, empieza el débil).",
            "Cierra anotando el nuevo BPM máximo de m-a."],
           "A esta altura el m-a debería empezar a sonar 'de corrido': si aún lo piensas nota a nota, baja 10 BPM y suelta.",
           "Nuevo récord de m-a anotado (o el motivo por el que no cayó)."),
        ex("Cejilla · F completo", 4,
           "El acorde entero: cejilla de 6 + forma de E.",
           ["F completo: dedo 1 cruza las 6 cuerdas en traste 1; dedos 2, 3 y 4 arman la forma de E encima (2 en 3ª/2, 3 en 5ª/3, 4 en 4ª/3).",
            "5 segundos presionando y sonando cuerda a cuerda, 10 de descanso (este cansa más), 6 repeticiones.",
            "Es exactamente tu ejercicio del día 7 (cejilla en traste 5) más la forma de E: ya hiciste las dos mitades por separado.",
            "No esperes 6/6 hoy: 4 cuerdas sonando es un primer F real."],
           "3ª y 4ª cuerda son las rebeldes de siempre; rueda el dedo 1 hacia el canto.",
           "En 2 de 6 intentos suenan 5 o más cuerdas.",
           chords=("F",)),
        ex("Ritmo · backbeat en la progresión", 6,
           "Los acentos del día 5 llegan a C-G-Am-F.",
           ["Corcheas ↓↑ en C-G-Am-F a 58 BPM (F parcial en su compás), 4 compases de repaso.",
            "Acentúa 2 y 4 (backbeat) durante 8 compases.",
            "Luego el patrón D-DU-UD-U con acento en el ↑ del 3, 8 compases.",
            "Escalera de 4 BPM por cada 4 compases limpios."],
           "El backbeat tiene que oírse con los ojos cerrados: grábate 8 compases con la app y compruébalo.",
           "8 compases con backbeat audible + BPM anotado."),
        ex("Cambios · G↔F y C↔F", 4,
           "El par nuevo más difícil hasta ahora.",
           ["60 segundos G↔F (parcial o completo, el que te salga: anota cuál usaste).",
            "30 segundos de descanso.",
            "60 segundos C↔F a superar récord.",
            "Anota ambos."],
           "En G→F todo el bloque viaja hacia abajo y adelante: piensa 'caer' sobre el F, no 'armarlo'.",
           "Dos récords anotados, con nota de si el F fue parcial o completo."),
        ex("Voz + guitarra · anticipación con F", 8,
           "El nivel 2 del día 4, sobre la progresión con F.",
           ["C-G-Am-F en negras a 58 BPM.",
            "Nivel 1 (3 min): nombra el acorde siguiente en el pulso 4 del compás anterior.",
            "Nivel 2 (5 min): canta la tónica del acorde SIGUIENTE en el pulso 4 (la voz llega al fa ANTES que la mano llegue al F). Es difícil de verdad: es el corazón de cantar tocando.",
            "Si se cae, vuelve al nivel 1 dos compases y reintenta."],
           "La voz adelantada 'tira' de la mano hacia el cambio: cuando funcione, el C↔F se te va a hacer más fácil, no más difícil.",
           "4 compases seguidos del nivel 2."),
        cierre("C-G-Am-F"),
    ],
})

DAYS.append({  # Día 11
    "tema": W2, "modo": "Repetir y subir", "foco": "F completo en movimiento",
    "ex": [
        ACT,
        ex("Arpegio digitado · p-m-a-m por la progresión", 5,
           "El patrón del día 6 recorre C-G-Am-F.",
           ["Un compás de p-m-a-m en cada acorde de C-G-Am-F (F parcial; p toca 4ª cuerda en el F).",
            "Metrónomo a 55 BPM o tu máximo anotado.",
            "2 vueltas limpias → +5 BPM.",
            "Último minuto: solo el compás de F en loop, hasta que el patrón no se entere de que es F."],
           "En el F, m y a pisan cuerdas pisadas con cejilla: si suenan sordas, el problema es la cejilla, no la derecha.",
           "2 vueltas completas limpias; anota el BPM."),
        ex("Cejilla · escalera del F completo", 4,
           "Del acorde estático al cambio real.",
           ["Peldaño 1: F completo, 5 segundos sonando cuerda a cuerda. 2 repeticiones.",
            "Peldaño 2: F completo y 3 rasgueos ↓ limpios. 2 repeticiones.",
            "Peldaño 3: cambio C→F lento sin metrónomo, 8 viajes.",
            "Peldaño 4 (si llegaste): C→F a un pulso de 50 BPM, 4 viajes.",
            "Sube de peldaño solo cuando el anterior salga; anota en cuál quedaste."],
           "La escalera es la medida: no importa el peldaño de hoy, importa que mañana sea el mismo o uno más.",
           "Peldaño alcanzado anotado."),
        ex("Ritmo · patrón completo a escalera", 6,
           "D-DU-UD-U + acentos, subiendo BPM toda la semana.",
           ["C-G-Am-F con D-DU-UD-U y acento en 2 y 4, partiendo 2 BPM bajo tu récord.",
            "4 compases limpios → +4 BPM; 2 caídas → −4.",
            "Cierra con 8 compases seguidos al máximo BPM limpio del bloque."],
           "Récord con el péndulo tieso no vale: el groove viaja con el BPM o no viaja.",
           "Nuevo BPM máximo del patrón anotado."),
        ex("Cambios · C↔F a récord (60 s)", 4,
           "Todo el bloque para el cambio que importa.",
           ["60 segundos C↔F con el contador. F completo si el peldaño 3 de hoy salió; si no, parcial (anota cuál).",
            "60 segundos de descanso sacudiendo la mano.",
            "60 segundos de revancha.",
            "Anota récord y tipo de F."],
           "La cejilla cansada del bloque anterior es parte del entrenamiento: los récords en fatiga consolidan más.",
           "Récord de C↔F anotado (con tipo de F)."),
        ex("Voz + guitarra · cantar los grados de la progresión", 8,
           "La teoría nueva (grados) entra por la voz, no por lección.",
           ["C-G-Am-F es, en grados, 1-5-6-4 de la escala de do. No hay más teoría que esa frase.",
            "Nivel 1 (3 min): en negras, canta el NÚMERO del grado en el pulso 1: 'UNO... CINCO... SEIS... CUATRO' (con la altura de la tónica de cada acorde, la misma que ya cantas).",
            "Nivel 2 (3 min): tararea una melodía libre de 4 compases sobre la progresión; repítela igual 2 veces.",
            "Nivel 3 (2 min): la misma melodía con la derecha en D-DU-UD-U.",
            "Miles de canciones son exactamente 1-5-6-4: lo que cantas hoy sirve para todas."],
           "Cantar el número con la altura correcta une teoría y oído en un solo gesto.",
           "8 compases cantando grados afinados + melodía repetida 2 veces igual."),
        cierre("C-G-Am-F"),
    ],
})

DAYS.append({  # Día 12
    "tema": W2, "modo": "Repetir y subir", "foco": "F en contexto y elegir la canción",
    "ex": [
        ACT,
        ex("Arpegio digitado · patrones combinados", 5,
           "Todos los patrones de dos semanas, seguidos.",
           ["Sobre C-G-Am-F: un compás p-i-m-a, un compás p-a-m-i, un compás p-m-a-m, un compás m-a-m-a. Esa vuelta de 4 compases es EL ejercicio.",
            "Metrónomo a 55 BPM; 2 vueltas limpias → +5 BPM.",
            "La gracia es el cambio de patrón por compás: el cerebro no puede piloto-automático."],
           "Entre patrones no hay pausa: la última nota de uno y la primera del otro están a un clic.",
           "2 vueltas de la secuencia completa limpias; anota el BPM."),
        ex("Cejilla · F dentro de la progresión", 4,
           "El F deja de ser ejercicio y pasa a ser música.",
           ["C-G-Am-F, UN rasgueo ↓ por compás a 50 BPM, con F completo: 8 vueltas.",
            "Toda la atención en el compás de F: que suene, aunque el rasgueo sea uno solo.",
            "Si el F no suena 2 vueltas seguidas, baja a F parcial 2 vueltas y retoma el completo.",
            "Anota cuántas vueltas de 8 sonó el F completo."],
           "Un solo rasgueo bueno por compás vale más que cuatro sucios: hoy el patrón no importa, el F sí.",
           "El F completo suena en 4 de 8 vueltas."),
        ex("Ritmo · el patrón al récord de la semana", 6,
           "Consolidación: el patrón se toca 'de verdad'.",
           ["C-G-Am-F, D-DU-UD-U con backbeat, al BPM récord anotado ayer: 16 compases seguidos.",
            "Si sale, +4 BPM y otros 16.",
            "Grábate una pasada con la app y escúchala: ¿se oye el acento? ¿el F rompe el flujo?",
            "Anota el veredicto de tu propia escucha."],
           "Escucharse grabado es el feedback más honesto que existe: úsalo.",
           "16 compases al récord + auto-veredicto anotado."),
        ex("Cambios · Em↔F y C↔F", 4,
           "Par nuevo y la revancha diaria.",
           ["60 segundos Em↔F con el contador (viaje corto: parecido al Am↔F).",
            "30 segundos de descanso.",
            "60 segundos C↔F: a superar el récord de ayer.",
            "Anota ambos."],
           "A estas alturas el C↔F ya no se piensa: si aún lo piensas dedo a dedo, haz 4 viajes lentos mirando y vuelve al récord.",
           "Dos récords anotados."),
        ex("Voz + guitarra · elegir y montar TU canción", 8,
           "Mañana se canta una canción completa: hoy se elige y se arma.",
           ["Elige una canción que conozcas bien y que sea 1-5-6-4 (C-G-Am-F). Candidatas si no se te ocurre ninguna: 'Zombie' (The Cranberries), 'No Woman No Cry' (Bob Marley, casi), 'Yerbatero' (Juanes) o cualquier balada pop de los últimos 30 años: la vuelta 1-5-6-4 está en miles. Anota cuál elegiste.",
            "Nivel 1 (3 min): rasguea la vuelta en negras y RECITA (hablada) la primera estrofa encima, acomodando las sílabas.",
            "Nivel 2 (4 min): cántala. Derecha en negras; si la voz se cae, la derecha SIGUE.",
            "Guarda la letra a mano para mañana."],
           "No busques la tonalidad original de la canción: cántala donde te acomode sobre TU C-G-Am-F.",
           "Una estrofa cantada de principio a fin con la derecha continua (aunque haya errores)."),
        cierre("C-G-Am-F", "Anota la canción elegida."),
    ],
})

DAYS.append({  # Día 13
    "tema": W2, "modo": "Aplicar", "foco": "La canción completa",
    "ex": [
        ACT,
        ex("Arpegio digitado · intro de la canción", 5,
           "El arpegio se vuelve arreglo: la intro de tu canción.",
           ["2 vueltas de p-i-m-a sobre C-G-Am-F, lento y bonito (55 BPM): esa es tu intro.",
            "2 vueltas de p-m-a-m.",
            "Elige cuál de las dos suena mejor como intro y tócala 2 veces más, ya sin metrónomo, con la dinámica que te pida.",
            "Anota cuál elegiste: mañana abre el test con ella."],
           "Sin metrónomo no significa sin pulso: el pulso ahora es tuyo.",
           "Una intro de 2 vueltas elegida y tocada 2 veces seguidas."),
        ex("Cejilla · calentamiento de F para la canción", 4,
           "Dosis de mantención antes de usarlo en serio.",
           ["4 repeticiones de F completo con la rutina de 5 segundos.",
            "8 cambios C→F a un pulso lento.",
            "4 vueltas de C-G-Am-F con un ↓ por compás, F completo.",
            "Listo: el F queda caliente para la canción."],
           "Hoy la cejilla es medio para un fin: no busques récord, busca que el F esté disponible.",
           "El F suena en 3 de las 4 vueltas."),
        ex("Ritmo · 16 compases sin red", 6,
           "El acompañamiento exacto que usará la canción.",
           ["C-G-Am-F con D-DU-UD-U y backbeat, al BPM en que te salga CÓMODO (no al récord: la canción necesita margen para la voz).",
            "16 compases seguidos, 2 veces.",
            "Última pasada: cierra los ojos la mitad de los compases.",
            "Ese BPM cómodo es el BPM de tu canción: anótalo."],
           "Cómodo = puedes pensar en otra cosa mientras tocas. Ese es el umbral que la voz necesita.",
           "2 × 16 compases y el BPM de canción anotado."),
        ex("Cambios · repaso exprés de récords", 4,
           "Mantención de los récords de la semana.",
           ["30 segundos C↔G a récord.",
            "30 segundos Am↔F.",
            "60 segundos C↔F.",
            "30 segundos del par que quieras. Anota lo que caiga."],
           "Bloque corto y intenso: los récords se defienden con visitas frecuentes, no largas.",
           "Cuatro sprints hechos, récords anotados si cayeron."),
        ex("Voz + guitarra · LA CANCIÓN", 8,
           "Todo el curso hasta aquí, junto.",
           ["Tu canción de ayer, al BPM cómodo anotado: intro de arpegio (2 vueltas) y entra la voz con la derecha en negras.",
            "Pasada 1: estrofa + coro con negras.",
            "Pasada 2: sube la derecha a D-DU-UD-U donde te atrevas; si la voz se cae, la derecha baja a negras SOLA, sin parar.",
            "Pasada 3: de principio a fin, la mejor que tengas. Grábala con la app.",
            "Escúchala 30 segundos: anota UNA cosa a mejorar mañana."],
           "La regla de oro de tocar y cantar: la derecha es el metrónomo y no negocia; la voz y la izquierda se suben a ella.",
           "Una pasada completa grabada + una mejora anotada."),
        cierre("C-G-Am-F", "Deja lista la letra para el test de mañana."),
    ],
})

DAYS.append({  # Día 14 — test frío
    "tema": W2, "modo": "Test frío", "foco": "Medir las dos semanas",
    "ex": [
        ex("Activación mínima", 2,
           "Como el día 7: afinar, postura, nada de calentar lo medido.",
           ["Afina con la app, siéntate bien.",
            "8 compases de péndulo al aire a 60 BPM y directo a los tests."],
           "En frío se mide lo aprendido; en caliente, lo ensayado.",
           "Listo para medir."),
        ex("TEST · arpegios", 5,
           "m-a y la secuencia combinada, en frío.",
           ["m-a en Am a 55 BPM, 8 compases: ¿parejo? Anota (compara con el día 7).",
            "La secuencia del día 12 (p-i-m-a / p-a-m-i / p-m-a-m / m-a-m-a por compás) sobre C-G-Am-F, 1 vuelta al BPM anotado.",
            "Resto del bloque: libre en el patrón que se haya caído."],
           "El m-a del día 7 contra el de hoy: esa diferencia es el hilo nuevo funcionando.",
           "Resultados anotados (m-a sí/no + BPM; secuencia sí/no)."),
        ex("TEST · cejilla y F", 4,
           "La medición contra la línea base del día 7.",
           ["En frío: cejilla en traste 5, 6 cuerdas, un intento. ¿Cuántas suenan? (día 7 anotaste tu línea base: compárala).",
            "En frío: F completo, un intento: ¿cuántas de 6?",
            "60 segundos C↔F con el contador: récord de la quincena.",
            "Anota los tres números."],
           "Tres números contra el día 7 y el día 8: eso es progreso medible de cejilla en 7 días.",
           "Tres mediciones anotadas."),
        ex("TEST · ritmo", 6,
           "El patrón completo a máxima exigencia.",
           ["D-DU-UD-U con backbeat en C-G-Am-F al BPM récord: 16 compases seguidos, en frío.",
            "Si sale, +4 BPM y reintenta. Si no, anota compás y BPM real.",
            "Resto: práctica libre del patrón."],
           "El BPM de 16 compases en frío es tu 'BPM verdadero': el que usarás la semana 3.",
           "BPM verdadero anotado."),
        ex("TEST · cambios", 4,
           "Los dos pares testigo de la quincena.",
           ["60 segundos C↔G: compara con día 1 y día 7.",
            "30 segundos de descanso.",
            "60 segundos Am↔F.",
            "Anota ambos."],
           "C↔G lleva 14 días de curva: debería estar claramente sobre el día 1.",
           "Dos récords anotados con sus comparaciones."),
        ex("TEST · la canción en frío", 8,
           "La prueba final de la quincena: música de verdad, sin calentar.",
           ["Tu canción completa: intro de arpegio + estrofa y coro cantados, al BPM cómodo. En frío, a la primera.",
            "Grábala con la app.",
            "Escúchala entera. Anota: ¿la derecha se detuvo? ¿el F sonó? ¿la voz sobrevivió a los cambios?",
            "Segunda pasada libre aplicando lo que escuchaste."],
           "Esto —una canción tocada y cantada— es lo que hace 14 días no podías hacer: escúchalo con esa vara.",
           "Canción grabada en frío + tres respuestas anotadas."),
        ex("Cierre · registro de la quincena", 1,
           "El contrato para la semana 3.",
           ["Junta los resultados de los 5 tests.",
            "Escribe: lo más mejorado, lo más estancado, y qué canción quieres para las semanas 3-4.",
            "Con esto se calibra lo que viene."],
           "Números y una decisión: así se cierra un ciclo.",
           "Registro completo en las notas de la app."),
    ],
})


def render():
    parts = []
    for i, day in enumerate(DAYS, start=1):
        week = 1 if i <= 7 else 2
        dow = i - (week - 1) * 7
        mins = sum(e["min"] for e in day["ex"])
        assert mins == 30, f"día {i}: {mins} min"
        arts = []
        for n, e in enumerate(day["ex"], start=1):
            steps = "".join(f"<li>{s}</li>" for s in e["steps"])
            chords = chord_svgs(e["chords"])
            arts.append(
                f'<article class="exercise"><div class="exhead"><span>{n}</span><div>'
                f'<h3>{e["t"]}</h3><small>{e["min"]} min</small></div></div>\n'
                f'<div class="brief"><b>Qué harás:</b> {e["brief"]}</div>\n'
                f'<details><summary>Instrucciones paso a paso</summary><div class="detail"><ol>{steps}</ol>{chords}\n'
                f'<div class="watch"><b>Qué observar:</b> {e["watch"]}</div>'
                f'<div class="pass"><b>Criterio para pasar:</b> {e["crit"]}</div></div></details></article>'
            )
        parts.append(
            f'<section class="day" id="day-{i}" data-day="{i}" data-week="{week}">\n'
            f'<div class="dayhead"><div><div class="eyebrow">Semana {week} · Día {dow} · Día {i}/182 · v2</div>'
            f'<h2>{day["tema"]}</h2><p>{day["modo"]} · 30 min · foco: {day["foco"]}</p></div></div>\n'
            + "".join(arts)
            + "</section>"
        )
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"{OUT.name}: {len(DAYS)} días, {OUT.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    render()
